plugins { id 'com.android.application' }

android {
    namespace 'com.uam.cientodentistas'
    compileSdk 36

    defaultConfig {
        applicationId 'com.uam.cientodentistas'
        minSdk 23
        targetSdk 36
        versionCode 30
        versionName '3.0.13-randomized-specialties'
    }
}
