const fs=require('fs'),vm=require('vm'),path=require('path');
const ROOT=path.join(process.cwd(),'app','src','main','assets');
const files=['english_overrides_01.js','english_overrides_02.js','english_overrides_03.js','english_overrides_03_011_020.js','english_overrides_03_021_030.js','english_overrides_03_031_040.js','english_overrides_03_041_050.js','english_overrides_03_051_075.js','english_overrides_03_076_100.js','english_overrides_04.js','english_overrides_04_031_055.js','english_overrides_04_056_080.js','english_overrides_04_081_100.js','english_overrides_05.js','english_overrides_06.js','english_auto_07_12.js','english_auto_13_18.js','english_auto_19_24.js','english_auto_25_30.js','english_auto_31.js','english_auto_32_45.js','english_auto_global_cleanup.js'];
const ctx={window:{},console};vm.createContext(ctx);for(const f of files)vm.runInContext(fs.readFileSync(path.join(ROOT,f),'utf8'),ctx,{filename:f});const w=ctx.window;
const spanish=['qué','cuales','cuáles','cómo','como','cuando','deben','debe','paciente','pacientes','dientes','diente','tejido','tejidos','evaluación','evaluacion','diagnóstico','diagnostico','tratamiento','selección','seleccion','prótesis','protesis','odontología','odontologia','salud','atención','atencion','medicación','medicacion','emergencias','documentación','documentacion','relación','relacion','corresponde','relaciona','considerarse','revisarse','valorar','valoración','valoracion','fundamentales','prevención','prevencion','higiene','población','poblacion','planificación','planificacion','historia','función','funcion','adaptación','adaptacion','expediente','lesiones','enfermedades','síntomas','sintomas','signos','principios','espacio','presión','presion','método','metodo','manejo','recursos','participación','participacion','competencia','encerado','ancho','coronaria','ángulos','angulos','transición','transicion','líneas','lineas','anatomía','anatomia','contorno','manchas','concentración','concentracion','aplicación','aplicacion','protocolo','rodillos','montaje','procesamiento','polimerización','polimerizacion','impresión','impresion','cubeta','sellado','rebasado','mucosa','blanqueamiento','diseño','sonrisa','restauración','restauracion','inflamación','inflamacion','infección','infeccion','traumatología','traumatologia','geriátrica','geriatrica','legislación','legislacion','bioética','bioetica','fotografía','fotografia','ortodoncia','periodonto','farmacología','farmacologia','anestésicos','anestesicos','endodóntico','endodontico','radiografías','radiografias','cáncer','cancer','oclusión','oclusion','reorganización','reorganizacion'];
function answers(q){if(Array.isArray(q.answers))return q.answers.map(x=>typeof x==='string'?x:(x?.text??x?.[0]??''));if(Array.isArray(q.a))return q.a.map(x=>Array.isArray(x)?x[0]:(x?.text??''));return []}
function qsrc(q){return String(q.question??q.q??q.open_q??'')}
function translate(i,q){
 if(i<=6){const ov=w.DentistasEnglishOverrides?.[q.id];if(!ov?.[0])throw Error('missing override question '+q.id);for(let j=0;j<answers(q).length;j++)if(!ov[1]?.[j])throw Error('missing override answer '+q.id+' #'+j);return [ov[0],ov[1]]}
 const fn=i<=12?w.DentistasEnglishAutoTranslate:i<=18?w.DentistasEnglishAutoTranslate1318:i<=24?w.DentistasEnglishAutoTranslate1924:i<=30?w.DentistasEnglishAutoTranslate2530:i===31?w.DentistasEnglishAutoTranslate31:w.DentistasEnglishAutoTranslate3245;
 if(!fn?.translate)throw Error('missing translator category '+i);
 return [fn.translate(qsrc(q)),...answers(q).map(a=>fn.translate(a))];
}
let total=0,issues=[];
for(let i=1;i<=45;i++){const raw=JSON.parse(fs.readFileSync(path.join(ROOT,'bank44_original_'+String(i).padStart(2,'0')+'.json'),'utf8'));const qs=Array.isArray(raw)?raw:raw.questions;if(!Array.isArray(qs)||qs.length!==100){issues.push('category '+i+' count '+(qs?.length??'invalid'));continue}const ids=new Set();for(const q of qs){total++;if(ids.has(q.id))issues.push('duplicate id '+q.id);ids.add(q.id);try{for(const s of translate(i,q)){const t=String(s||'');if(!t.trim())issues.push('empty '+q.id);if(/[¿¡áéíóúñüÁÉÍÓÚÑÜ]/.test(t))issues.push('Spanish punctuation/accent '+q.id+' => '+t);if(/\bwhat\s+what\b|\bwhich\s+which\b|\bwhat\s+qué\b/i.test(t))issues.push('bad construction '+q.id+' => '+t);for(const word of spanish){const re=new RegExp('(^|[^A-Za-zÁÉÍÓÚÑÜáéíóúñü])'+word.replace(/[.*+?^()|[\]\\]/g,'\\$&')+'([^A-Za-zÁÉÍÓÚÑÜáéíóúñü]|$)','i');if(re.test(t)){issues.push('Spanish residue '+q.id+' => '+t);break}}}}catch(e){issues.push(e.message)}}if(ids.size!==100)issues.push('category '+i+' unique ids '+ids.size)}
const index=fs.readFileSync(path.join(ROOT,'index.html'),'utf8'),app=fs.readFileSync(path.join(ROOT,'app.js'),'utf8');for(const f of files)if(!index.includes(f))issues.push('index missing '+f);for(const n of ['DentistasEnglishAutoTranslate','DentistasEnglishAutoTranslate1318','DentistasEnglishAutoTranslate1924','DentistasEnglishAutoTranslate2530','DentistasEnglishAutoTranslate31','DentistasEnglishAutoTranslate3245'])if(!app.includes(n))issues.push('app route missing '+n);if(total!==4500)issues.push('total questions '+total);
if(issues.length){console.error(JSON.stringify({ok:false,total,issueCount:issues.length,issues:issues.slice(0,100)},null,2));process.exit(1)}console.log(JSON.stringify({ok:true,total,categories:45,questionsPerCategory:100,translationLayers:files.length}));
